apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nextjs-web-app
  labels:
    app: nextjs-web-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2        # how many pods we can add at a time
      maxUnavailable: 0  # maxUnavailable define how many pods can be unavailable
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nextjs-web-app
  template:
    metadata:
      labels:
        app: nextjs-web-app
    spec:
      containers:
      - name: nextjs-web-app
        image: _IMAGE_
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: nextjs-web-app-env
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          # limits:
          #   cpu: 200m
          #   memory: 512Mi
          # requests:
          #   cpu: 200m
          #   memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      imagePullSecrets:  # Specify image pull secrets
      - name: regsecret
      affinity:
      nodeSelector: {}   # Node labels for pod assignment
      tolerations: []    # List of node taints to tolerate
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh

